FROM node:16

# Create app directory
WORKDIR /home/openbackhaul/MApplicationAbbreviationExtractor 

# Install and app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
COPY package*.json ./

# install application by NPM
RUN npm install

# Bundle app source
COPY . .

EXPOSE 9091

#Command to start the application
CMD [ "node", "index.js" ]
